# Generated by Django 5.1 on 2024-10-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_idx_last_name_first_name'),
    ]

    operations = [
        migrations.RunSQL(sql="""
        INSERT INTO store_collection (title) VALUES('collection1')
        """,
        reverse_sql="""
        DELETE FROM store_collection WHERE title='collection1'
        """)
    ]
