# Generated by Django 5.1 on 2024-10-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20241009_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='demo',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=32),
        ),
    ]
