# Generated by Django 5.1.2 on 2024-11-10 12:01

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_collection_options_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='id',
        ),
    ]
