# Generated by Django 5.1.2 on 2024-11-10 12:16

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_id_field_form_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
