services:
  django_base_db:
    image: postgres:latest
    container_name: django_basic_db
    env_file:
      - ./postgres_env
    ports:
      - 5432:5432
    volumes:
      - ./z_project_db:/var/lib/postgresql/data
