# Generated by Django 5.1 on 2024-10-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaggetItem',
            new_name='TaggedItem',
        ),
    ]
